"use client"

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SearchProvider } from "@/app/context/SearchContext";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import { store } from "./redux/store";
import { Provider } from "react-redux";
import { CartProvider } from "./context/CartContext";
import "@fontsource/bebas-neue"; 
import "@fontsource/bebas-neue/400.css"; 
// import "@fontsource/bebas-neue/400-italic.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Book Store",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider store={store}>
          <CartProvider>
            <SearchProvider>
              <Header />
              {children}
              <Footer />
            </SearchProvider>
          </CartProvider>
        </Provider>
      </body>
    </html >
  );
}
